### ISSUE TITLE
Error in getting installId 

### ISSUE THREAD

**Issue by rmamtaventures** [Kumulos/KumulosSdkReactNative#15]
I'm using this:- 
import Kumulos from "kumulos-react-native";
 const id = await Kumulos.getInstallId();

Error:- Cannot read property 'getInstallId' of null.

**Comment by rmamtaventures** [comment]
I'm using same Kumulos object for setting events. Events are working fine. But showing it null in case of getting install id.

**Comment by cgwyllie** [comment]
Hello, closing as resolved through support.
